spring:
  application:
    name: miniProgramDemo
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniProgramDemo
    username: root
    password: abc8909389
  redis:
    host: remote
    port: 26379
  mail:
    host: smtp.qq.com
    username: ${emailUsername}
    password: ${emailPassword}
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
server:
  port: 7001
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
weixin:
  appid: ${WECHAT_APPID}
  secret: ${WECHAT_SECRET}
